MAXANUM_POWER = 100
ENA_GPIO = 5

BACK_LEFT_FORWARD_GPIO = 6
BACK_LEFT_BACKWARD_GPIO = 12

FRONT_LEFT_FORWARD_GPIO = 13
FRONT_LEFT_BACKWARD_GPIO = 16

BACK_RIGHT_FORWARD_GPIO = 19
BACK_RIGHT_BACKWARD_GPIO = 20

FRONT_RIGHT_FORWARD_GPIO = 26
FRONT_RIGHT_BACKWARD_GPIO = 21
