MAXANUM_POWER = 100
ENA_GPIO = 22

BACK_LEFT_FORWARD_GPIO = 23
BACK_LEFT_BACKWARD_GPIO = 24

FRONT_LEFT_FORWARD_GPIO = 23
FRONT_LEFT_BACKWARD_GPIO = 24

BACK_RIGHT_FORWARD_GPIO = 23
BACK_RIGHT_BACKWARD_GPIO = 24

FRONT_RIGHT_FORWARD_GPIO = 23
FRONT_RIGHT_BACKWARD_GPIO = 24
