MAXANUM_POWER = 100
ENA_GPIO = 5

# IR
LEFT_LED_GPIO = 15
MID_LED_GPIO = 18
RIGHT_LED_GPIO = 23

# Maxanum
BACK_LEFT_FORWARD_GPIO = 26
BACK_LEFT_BACKWARD_GPIO = 21

FRONT_LEFT_FORWARD_GPIO = 13
FRONT_LEFT_BACKWARD_GPIO = 16

BACK_RIGHT_FORWARD_GPIO = 19
BACK_RIGHT_BACKWARD_GPIO = 20

FRONT_RIGHT_FORWARD_GPIO = 6
FRONT_RIGHT_BACKWARD_GPIO = 12

# Ultrasonic
LEFT_TRIG_GPIO = 10
LEFT_ECHO_GPIO = 25
MID_TRIG_GPIO = 9
MID_ECHO_GPIO = 8
RIGHT_TRIG_GPIO = 11
RIGHT_TRIG_GPIO = 7

